### ISSUE TITLE
Build fails - no version.m4

### ISSUE THREAD

**Issue by xbglowx** [ingenthr/memcachetest#14]
Sorry for my ignorance, but I am trying to build memcachetest and I get the following:

memcachetest]$ automake
configure.ac:2: /usr/bin/m4: cannot open `m4/version.m4': No such file or directory
autom4te: /usr/bin/m4 failed with exit status: 1
automake: autoconf failed with exit status: 1

If I copy /usr/share/autoconf/m4sugar/version.m4 to m4 dir, I get:

memcachetest]$ automake
configure.ac: no proper invocation of AM_INIT_AUTOMAKE was found.
configure.ac: You should verify that configure.ac invokes AM_INIT_AUTOMAKE,
configure.ac: that aclocal.m4 is present in the top-level directory,
configure.ac: and that aclocal.m4 was recently regenerated (using aclocal).
configure.ac: required file `config/install-sh' not found
configure.ac: required file`config/missing' not found
Makefile.am: required file `config/depcomp' not found
/usr/share/automake-1.9/am/depend2.am: am__fastdepCC does not appear in AM_CONDITIONAL
/usr/share/automake-1.9/am/depend2.am: AMDEP does not appear in AM_CONDITIONAL

OS: CentOS 5.4
RPMs Installed:
   automake-1.9.6-2.1
   autoconf-2.59-12
   libtool-1.5.22-7.el5_4
   make-3.81-3.el5
   imake-1.0.2-3

**Comment by ingenthr** [comment]
you'll need to run config/autogen.sh first.  You'll also need to have git available and in your path.  There is a script called from there that will generate the version.sh
